exports.nsfw = require('./nsfw')
exports.weeaboo = require('./weeaboo')
exports.downloader = require('./downloader')
exports.fun = require('./fun')
exports.misc = require('./misc')
exports.meme = require ('./meme')
exports.nandostatus =require ('./nandostatus')